### ISSUE TITLE
Error when running fiddle with Quill 1.0.0

### ISSUE THREAD

**Issue by julienlafont** [scalafiddle/scalafiddle-core#14]
Hello,

I open a ticket because Quill 1.0.0 seems to not work with ScalaFiddle (or something is misconfigured).

Steps to reproduce :

1. Add "quill 1.0.0" (from "Show all versions") to a new Fiddle
2. Type `println("hello world")`
3. Run

Theses operations gave the following output :

> ScalaFiddle.scala:-5: ERROR: Library io.getquill %%% quill-sql % 1.0.0 is not allowed

**Comment by ochrons** [comment]
It seems that the compiler side has not updated the latest library information from the editor. Same also occurs with latest Diode and Boopickle libs. Need to investigate.

**Comment by ochrons** [comment]
Restarting the compiler services fixed this. Still don't know why it didn't automatically update the libs although in the logs it seemed to do it.
