### ISSUE TITLE
Simple snippet compiles for long period and then gets an error (500 response code)

### ISSUE THREAD

**Issue by vpavkin** [scalafiddle/scalafiddle-core#15]
```scala
val stoi: String => Int = _.toInt

println(stoi("42"))
```

**Comment by olafurpg** [comment]
I am unable to reproduce, the snippet compiled and ran immediately here https://scalafiddle.io/sf/n6K8wjN/0

**Comment by vpavkin** [comment]
Yep, probably that was some temporary glitch. Thanks, closing!

**Comment by ochrons** [comment]
Yea, there is no monitoring of the service, so if you see problems, best to report on the Gitter channel :)
