### ISSUE TITLE
Implement collaborative session sharing

### ISSUE THREAD

**Issue by schrepfler** [scalafiddle/scalafiddle-core#17]
While I really enjoy testing out code snippets on scalafiddle, I often wish I would be able to use it to interactively perform some quick pair programming session/interview similar to kobra.io.
I think it would be quite possible to extend the scalafiddle client to integrate with some push provider (ex. Firebase) and have a:
1. Ability to create a programming session which once registered with the push provider gives us a unique coding session URL.
2. Protocol to sync up the client state between the two clients. This includes i) code written by two parties ii) ability to write using two/more cursors at the same time on the code iii) show the popups when a client invokes the popup iv) sync up the execution stdout to all connected clients.

**Comment by ochrons** [comment]
This goes outside the scope of Scalafiddle, would probably fit better in the new Scastie.
