### ISSUE TITLE
println trims white space

### ISSUE THREAD

**Issue by kindu** [scalafiddle/scalafiddle-core#21]
<img width="1192" alt="screen shot 2017-10-17 at 08 57 26" src="https://user-images.githubusercontent.com/11808606/31653111-496b01d0-b319-11e7-8a62-56f3995ac68a.png">

**Comment by ochrons** [comment]
That's how HTML works, unfortunately. I suppose it should be wrapped in a <pre> block instead of <div> to get proper handling of whitespace.

**Comment by kindu** [comment]
Adding a `white-space: pre` CSS attribute could also work.

I spent an unholy amount of time trying to get my https://www.hackerrank.com/challenges/staircase/problem solution to work before I realized this bug was to blame. Definitely worth looking into.

**Comment by ochrons** [comment]
Ah, that CSS trick would be even better. I have a major update to ScalaFiddle coming soon (updates to Scala 2.12) so I'll incorporate this there :)

**Comment by kindu** [comment]
Thanks! Looking forward to it.

**Comment by ochrons** [comment]
Works now!

**Comment by kindu** [comment]
Yes it does! 🍾 💯
