### ISSUE TITLE
Speed up and Scala 2.12

### ISSUE THREAD

**Issue by AIMMOTH** [scalafiddle/scalafiddle-core#23]
Hello,

I made a concept with a servlet compiling Scala JS source, you can find it here https://github.com/aimmoth/scalajs-compiler-servlet 

It seems the fiddler code is using Scala 2.11. Is it possible to update to 2.12? I tried but there was a lot of deprecation.

Also, how do you speed up the compilation part? 

Thanks

**Comment by ochrons** [comment]
Probably best to have this discussion in Gitter 😄
