### ISSUE TITLE
Support -Ypartial-unification

### ISSUE THREAD

**Issue by LukaJCB** [scalafiddle/scalafiddle-core#27]
I think this would help a lot of us doing FP and 99.9% of the time, it should cause no issues at all. :)
We could always have a small toggle somewhere to turn it off if it does cause issues I guess (though I'm more than certain this will never happen in practice)

**Comment by ochrons** [comment]
Do you have some small piece of code I can test to verify the parameter is correctly being applied? Something that fails to compile without it.

**Comment by LukaJCB** [comment]
Sure,
```scala
import cats.implicits._
val x: List [Either[String, Int]] = List.empty
val y = x.sequence
```
