### ISSUE TITLE
Regular expression checking doesn't work with string anchors

### ISSUE THREAD

**Issue by jclem** [scalafiddle/scalafiddle-core#30]
In ScalaFiddle, this is `None` (see https://scalafiddle.io/sf/amxlC9O/0):

```scala
"""\Ahello""".r.findFirstIn("hello")
```

In Scastie, it's `Some(hello)`: https://scastie.scala-lang.org/ZUmFJMFgSNaGA2nrRXrUkA

**Comment by ochrons** [comment]
Scala.js uses JS regex engine, so it's not the same as on JVM.

**Comment by jclem** [comment]
Oh whoops, I didn't realize that ScalaFiddle uses Scala.js.

**Comment by ochrons** [comment]
There aren't many things that work differently from JVM, but regexes are one of them (for performance reasons) :)
