### ISSUE TITLE
Can't refactor use of scalatag SVG

### ISSUE THREAD

**Issue by Lasering** [scalafiddle/scalafiddle-core#32]
[This fiddle](https://scalafiddle.io/sf/AQnq262/0) works.

Now I want to refactor the `t` value to create circles with different radius [fiddle of it](https://scalafiddle.io/sf/tc3aXoD/0).

Seems like its an impossible job!

Without any return type annotation on the draw method, I get:
```
ScalaFiddle.scala:27: error: type mismatch;
 found   : collection.this.Seq[scalatags.this.JsDom.TypedTag[raw.this.SVGElement with raw.this.SVGTransformable with raw.this.SVGStylable with raw.this.SVGTests with raw.this.SVGExternalResourcesRequired with raw.this.SVGLangSpace{}]]
 required: .this.scalatags.JsDom.all.Modifier
    (which expands to)  generic.this.Modifier[raw.this.Element]
  Fiddle.print(draw(25))
                   ^
```

Since the imports are
```
import scalatags.JsDom.implicits._
import scalatags.JsDom.svgAttrs._
import scalatags.JsDom.svgTags._
```
seems like there is no way of returning a `.this.scalatags.JsDom.all.Modifier`.

`scalatags.JsDom.all` does not include SVG tags.

**Comment by ochrons** [comment]
These issues are only intended for bug reports on Scalafiddle itself. Please use the Gitter chat rooms (for example scala-js/scala-js) for discussion.
