### ISSUE TITLE
Regression: Server responded with 0: 

### ISSUE THREAD

**Issue by Atry** [scalafiddle/scalafiddle-core#35]
The following snippet is created some days ago, and it compiled at that time.
https://scalafiddle.io/sf/jTAPDnW/0 

Unfortunately, it does not compile now. Instead, the error message `Server responded with 0:` is shown.

**Comment by ochrons** [comment]
Works for me just fine. Did you try making some whitespace-only change to force a recompile, in case there is some caching issue?

**Comment by Atry** [comment]
It seems the server was down when I report this issue, other snippets did not compile at that time.

Fortunately it is good for now.
